FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements_api.txt requirements_api.txt
RUN pip install --no-cache-dir -r requirements_api.txt

WORKDIR "/data"
