FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements_pdf_parser.txt requirements_pdf_parser.txt
RUN pip install --no-cache-dir -r requirements_pdf_parser.txt

COPY pdf_parser/ pdf_parser/

WORKDIR /data
